modLoader="javafml"

loaderVersion="[25,)"

[[mods]]
modId="qui2ver"
version="${version}"

displayName="Quiver Restoration"
authors="Vatuu"
logoFile="icon.png"
description="Re-introduces the quiver item into the game."
credits="Have you tried FabricMC yet?"