modLoader="javafml"

loaderVersion="[25,)"

[[mods]]
modId="qui2ver"
version="${version}"

displayName="Quiver Restoration"
authors="Vatuu"
logoFile="icon.png"
description="This sure is a description."
credits="Have you tried FabricMC yet?"